# Generated by Django 3.1.6 on 2021-04-07 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04_psycho', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conners',
            old_name='conn_info',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='scl_90',
            old_name='scl_info',
            new_name='account',
        ),
    ]
